# Basic Docker Compose file for Dozzle - a lightweight log viewer for Docker containers
# Docker Hub: https://hub.docker.com/r/amir20/dozzle
# Official Website: https://dozzle.dev/
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      # Mount Docker socket to allow Dozzle to read container logs, read-only.
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
